root: true
env:
  'browser': true
  'node': true
  'vue/setup-compiler-macros': true
extends:
  - '@nuxtjs/eslint-config-typescript'
  - 'plugin:nuxt/recommended'
  - 'airbnb-base'
plugins: []
rules:
  'import/extensions': [
    'error',
    'ignorePackages',
    { js: 'never', ts: 'never' },
  ]
  'no-restricted-syntax': [
    'error',
    'ForInStatement',
    'LabeledStatement',
    'WithStatement',
  ]
  'object-curly-newline': [
    'error',
    {
      'ObjectExpression': { multiline: true, consistent: true },
      'ObjectPattern': { multiline: true, consistent: true },
      'ImportDeclaration': { multiline: true, consistent: true },
      'ExportDeclaration': { multiline: true, consistent: true },
    },
  ]
  'no-shadow': 'off'
  'no-unused-vars': 'off'
  '@typescript-eslint/no-shadow': 'error'
  '@typescript-eslint/no-unused-vars': 'error'
