customSyntax: 'postcss-html'
extends:
  - 'stylelint-config-standard-scss'
  - 'stylelint-stylistic/config'
  - 'stylelint-config-standard-vue/scss' # this should be place last
rules:
  'selector-class-pattern': null
